name: 'Install npm deps'
description: Install locked dependencies, including platform optional binaries.

runs:
  using: composite
  steps:
    - name: npm ci
      shell: bash
      run: npm ci --include=optional
